from setuptools import setup, find_packages

setup(
    name='sv',
    version='0.1',
    py_modules=['sv'],
    install_requires=[
        'boto3',
        'peewee',
        'peewee_validates',
        'pymysql',
        'flask',
        'pylint',
        'pytest',
        'pytest-cov',
        'pytest-mock',
        'pytest-watch',
        'pycryptodome',
        'mock',
        'pandas',
        'baseconvert',
        'simplejson',
        'pytz',
        'openpyxl',
        'mysql-connector-python'
    ],
    setup_requires=['pytest-runner'],
    tests_require=['pytest'],
)
